
const defaultDimensions = [
  { value: "age", label: "age" },
  { value: "location", label: "Location" },
  { value: "sex", label: "Sex" },
  { value: "reference_area", label: "Reference Area" },
  { value: "economic_class", label: "Economic Class" },
  { value: "time_period", label: "Time Period" },
  { value: "frequency", label: "Frequency" },
  { value: "education", label: "Education" },
  { value: "area_type", label: "Area Type" },
  { value: "marital_status", label: "Marital Status" },
  { value: "disablity_status", label: "Disability Status" },
  { value: "labour_market_status", label: "Labour Market Status" },
  { value: "household_type", label: "Household Type" },
  { value: "economic_activity", label: "Economic Activity" },
  { value: "occupation", label: "Occupation" },
  { value: "sector", label: "Sector" },
  { value: "status_in_employment", label: "Status in Employment" },
  { value: "government_level", label: "Government Level" },
  { value: "job", label: "Job" },
  { value: "weekly_hours_worked", label: "Weekly Hours Worked" },
  { value: "multiple_job_holding", label: "Multiple job holding" },
  { value: "duration", label: "Duration" },
  { value: "currency", label: "Currency" },
  { value: "quantile", label: "Quantile" },
  { value: "type_of_incapacity", label: "Type of incapacity" },
  { value: "migrant_status", label: "Migrant status" },
  { value: "type_of_volunteer_work", label: "Type of volunteer work" },
  { value: "place_of_birth", label: "Place of Birth" },
  { value: "citizenship", label: "Citizenship" },
  { value: "country_of_residence", label: "Country of residence" },
  {
    value: "country_of_previous_residence",
    label: "Country of previous residence",
  },
  { value: "country_of_destination", label: "Country of destination" },
  {
    value: "attendance_in_school_or_training",
    label: "Attendance in school or training",
  },
  { value: "consumer_price_index", label: "Consumer Price Index" },
];

module.exports = {
  defaultDimensions,
};
